### ISSUE TITLE
Possible causes for receiving a lot of SHTP_BAD_SN events for BNO085?

### ISSUE THREAD

**Issue by aentinger** [ceva-dsp/sh2#7]
I'm receiving a lot of `STHB_BAD_SN` events which all originate from [here](https://github.com/ceva-dsp/sh2/blob/main/shtp.c#L201-L206).

Interestingly enough, the sensor still works and data is successfully decoded. If you are taking a look at the linked code you can see that it just calls the event callback, but does not leave `rxAssemble` as it does for all other SHTP events/errors.

Can anyone from the maintainers (@kwalker-ceva , @dwheeler-ceva , @carlsondc-ceva) shed a light on this issue?

Note: I'm actively maintaining a CMake and C++ ready version of this repository over [here](https://github.com/pika-spark/pika-spark-sh2).

**Comment by dwheeler-ceva** [comment]
That error, SHTP_BAD_SN, is reporting that the sequence numbers in the SHTP packets aren't what the driver expected.  And, I suspect the cause is in the I2C HAL.  Due to limitations with the STM32 i2c library, we have to do two i2c reads for each transfer.  The first needs to read the header, with the transfer len, channel id and sequence number.  The second reads the full transfer, now that we know the length.  That first read was 4 bytes, to read the whole header initially.  At some point, though, we "optimized" it to read just two bytes since we only needed the length field.  Unfortunately, this causes the SHTP layer to miss half the sequence number updates, resulting in those errors you're seeing.  The fix is to simply change the I2C HAL back to reading 4 bytes when it reads the header.

**sh2-demo-nucleo/app/i2c_hal.c:**
```
// How many bytes to read when reading the length field
#define READ_LEN (4)   // CHANGE THIS FROM 2 to 4.
```

I have some bug fixes ready to push to the repo, including this one.  I'll plan on doing that this week.

Anyway, as you noticed, this error doesn't cause the rxAssemble function to abort assembly - it proceeds to assemble and deliver the message, despite the missed sequence number.  And, as you reported, this doesn't actually corrupt the data.

**Comment by aentinger** [comment]
Hi @dwheeler-ceva :coffee: :wave: 

Thank you for the fast response, it's good to see that there's still someone monitoring this repository :wink: .

That being said I use SPI with the max. allowed bitrate (of 3 MBit/s) to communication with the BNO085. It is used for a [Linux userspace driver interfacing with a BNO085](https://github.com/pika-spark/pika-spark-bno085-driver) via spidev.

The actual SPI hal read code can be seen [here](https://github.com/pika-spark/pika-spark-bno085-driver/blob/main/bno085_hal.cpp#L59-L93), there's an **initial 4-byte transfer** followed by a subsequent `packet_size`-byte transfer. Can you maybe advise if you see something in there that could be causing the `SHTP_BAD_SN` issues I've reported?

**Comment by dwheeler-ceva** [comment]
I'll take a look.  Would it be possible to get a logic analyzer capture of the SPI bus activity?

**Comment by aentinger** [comment]
> I'll take a look.

Thank you. 🙇 

> Would it be possible to get a logic analyzer capture of the SPI bus activity?

Difficult, but doable. I try to geht you a trace by the end of this week 👍 .

**Comment by dave20874** [comment]
Alexander,

I reviewed your code briefly and I think I understand what's happening.
Your HAL performs two SPI reads to get the payload so the sequence numbers
are being incremented twice.  But the function doesn't send the data from
both reads up to the SHTP layer, it only sends the results of the second,
full-size read.  So the stream of data seen at the SHTP layer only has
every other sequence number.  This is similar to the bug I referred to
earlier that we were having with our I2C HAL.

The way to solve this is to either read all the SPI data with one SPI
transaction or report data from both reads to the SHTP layer with
rxAssemble.  The I2C HAL in our demo code does it the second way, but the
implementation is complicated as it requires a state machine to do two
different size reads, one for the header and one for the full transfer.
The SPI HAL in the demo code does it the first way using one SPI
transaction to read everything without deasserting CSN.

By one SPI transaction, I mean:
    * Assert CSN
    * A SPI transfer of 4 bytes to get header, (especially length field)
    * A SPI transfer of length-4 bytes to get the remainder.
    * Deassert CSN.

If CSN is deasserted and reasserted between reading the header and reading
the remainder, the sensor hub will treat the second read as a new read,
starting with a new header and incrementing the sequence number a second
time.

Dave

**Comment by aentinger** [comment]
Hi Dave :coffee: :wave: 

Thank you for taking a look at my SPI HAL read function. Your feedback has set me on the right path. However, fixing it proved trickier than I anticipated. I found myself trapped between a rock and a hard place as I could choose by either modifying the sh2 library or bypassing layers and pushing application logic (distinction between a header and payload read) down into the SPI layer (imho subsequent SPI reads should be atomic with CS always asserted and deasserted).

Ultimately I opted for pushing the application logic code (header read followed by payload read) up into the sh2 library - https://github.com/pika-spark/pika-spark-sh2/commit/f64c44e47b3fdb3c472d6e351577ecde174c0a19 . This drastically simplifies the glue logic connecting sh2 library to the SPI layer - https://github.com/pika-spark/pika-spark-bno085-driver/commit/6c2e9d254bf17e7725a25151f6634fb6b937843e .

As a result I am happy to report that I do not receive any sequence errors anymore :+1: .
